### ISSUE TITLE
A way to dismiss tooltip when it's anchored to a view, is focusable and on click of the anchorView

### ISSUE THREAD

**Issue by vpulpatil** [douglasjunior/android-simple-tooltip#100]
I have a scenario where I am showing a custom tooltip on a floating button, where following things should happen:
1. After clicking outside, it should not get clicked, keeping transparentOverlay=false
2. On tooltip click and the anchored view, the toolview should get dismissed.
3. and onDismiss(), some action needs to be performed.
For the above scenario, I used
```
.anchorView(anchoredView)
.text(getString(R.string.post_ad_tooltip_text))
.dismissOnOutsideTouch(false)
.dismissOnInsideTouch(true)
.transparentOverlay(false)
.focusable(true)
.animated(true)
.modal(true)
.contentView(R.layout.custom_tooltip_post_ad, R.id.tv_text)
.onDismissListener {
      //some operation
}
```

Request you for the solution, how should I do this.

**Comment by JonathanNet** [comment]
Yeah I have the same problem with onDismiss() and onDetach(); I just get nullpointer

**Comment by Armen101** [comment]
I have this problem too, Please fix it

**Comment by gilangarinata** [comment]
Anyone can fix this?

**Comment by douglasjunior** [comment]
I think that we have a confusion with the meaning of click inside and click outside.

- **dismissOnOutsideTouch** -> Closes when touched **outside the balloon**.
- **dismissOnInsideTouch** -> Closes when touched **inside the balloon**.
- **modal** -> Prevent the touch event to be propagated to the background views. 
- **focusable** -> Set focusable to the popupWindow and request focus em the ballon appears.
- **anchorView** -> Used just to calculate the ballon position.

If you guys think that the behaviour is buggy, please provide a reproducible demo.
