### ISSUE TITLE
Want to set margin from Right side

### ISSUE THREAD

**Issue by RGC1092** [douglasjunior/android-simple-tooltip#104]
I tried .margin property but it does not work for me
in my case, I have info icon on right side of the screen on click on this I open the tooltip
but when the  tooltip opens it touches the right side edge of the screen  so need to margin Right 
Add Particular Margins LEFT,RIGHT,TOP,BOTTOM

**Comment by psandroiddev** [comment]
Put this line to configContentView() method in SimpleTooltip.java class.

contentViewParams.setMargins(0,0,20,0);
