### ISSUE TITLE
Not able to set margin end

### ISSUE THREAD

**Issue by swatiomar** [douglasjunior/android-simple-tooltip#105]
I want to set margin end but not able to doing so. Actually the view is touching the sies of the screen. I want some margin from end. Please suggest the way how can I do it.

**Comment by hhirpara26** [comment]
Put this line to `configContentView()` method in `SimpleTooltip.java` class.

`        contentViewParams.setMargins(0,0,20,0);
`

**Comment by riya8080** [comment]
> I want to set margin end but not able to doing so. Actually the view is touching the sies of the screen. I want some margin from end. Please suggest the way how can I do it.

 you were able to resolve?
