### ISSUE TITLE
Clickable  Child Element

### ISSUE THREAD

**Issue by HarshLathigara1** [douglasjunior/android-simple-tooltip#106]
I Have Added setContentView And added CustomView As Tooltip
So And Have three Buttons in CustomView But When I m Adding OnClick Listner 
Its Not Working
Can Anyone  Tell Me How To Make it Possible

**Comment by HarshLathigara1** [comment]
I Have Added This Way
But Its Not Working 
txt_update = menuToolTip.findViewById(R.id.txt_update);
        txt_update.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
              
            }
        });

**Comment by douglasjunior** [comment]
Here is an example, that shows how to add click handler to child elements, like a Button.

https://github.com/douglasjunior/android-simple-tooltip/blob/a3310323295b6412d845c57692b0c19a74dcbd47/sample/src/main/java/io/github/douglasjunior/androidSimpleTooltip/sample/MainActivity.java#L182-L194

**Comment by HarshLathigara1** [comment]
Hello sir
Thank you for reply
I have tried this called already it's not working.

**Comment by douglasjunior** [comment]
The problem is in your internal element, and not in the Tooltip, the Sample Project is working.

**Comment by HarshLathigara1** [comment]
Here is my Code Its still Not working.  
```java
menuToolTip = new SimpleTooltip.Builder(MainActivity.this)
                .anchorView(view)
                .gravity(Gravity.BOTTOM)
                .modal(true)
                .focusable(true)
                

                .arrowColor(ContextCompat.getColor(this, R.color.red))
                .text(getString(R.string.app_name))
                .contentView(R.layout.tooltip_new)
                .build();

menuToolTip.findViewById(R.id.txt_logout).setOnClickListener(new View.OnClickListener() {
             @Override
             public void onClick(View v) {
                    System.out.println("clicked=====");
             }
});


menuToolTip.show();
```

**Comment by douglasjunior** [comment]
Please, also send the content of the `R.layout.tooltip_new` XML layout.

**Comment by HarshLathigara1** [comment]
I had downgrade library version it's working now for me it's not working in latest version

**Comment by HarshLathigara1** [comment]
menuToolTip.findViewById(R.id.txt_edit).setText
method
