### ISSUE TITLE
Dynamic scrolling to the target view

### ISSUE THREAD

**Issue by majedalmoqbeli** [douglasjunior/android-simple-tooltip#117]
Dear @douglasjunior ,

I have an screen that contain a lot of elements inside ScrollView when I use Tooltips to any view that not shown for example in the bottom of screen. I want the app scroll to this view to show tooltip correctly.

I use `focusable(true) ` but don't work.
Any help. Thank You.

**Comment by douglasjunior** [comment]
Hi @majedalmoqbeli, this library don't scroll automatically the views, you need to scroll manually when the tooltip opens. For example, you can add an `OnShowListener` to know when the tooltip opens.
