### ISSUE TITLE
border

### ISSUE THREAD

**Issue by omarsaadosak** [douglasjunior/android-simple-tooltip#120]
Ho I can add border for the tooltip with it's arrow?

**Comment by douglasjunior** [comment]
The default arrow is a  canvas Drawable https://github.com/douglasjunior/android-simple-tooltip/blob/master/library/src/main/java/io/github/douglasjunior/androidSimpleTooltip/ArrowDrawable.java

It's not trivial to add the border like you need.

The best options will be to set a custom as an Image: 

https://github.com/douglasjunior/android-simple-tooltip/blob/21083fce4495666cf29f062b23a8e2838cbabc46/sample/src/main/java/io/github/douglasjunior/androidSimpleTooltip/sample/MainActivity.java#L211-L220
