### ISSUE TITLE
how to change text size 

### ISSUE THREAD

**Issue by dat2309** [douglasjunior/android-simple-tooltip#121]
i want to change text size, how to do that

**Comment by douglasjunior** [comment]
If you don't provide a custom `contentView`, a default one is created for you:

https://github.com/douglasjunior/android-simple-tooltip/blob/21083fce4495666cf29f062b23a8e2838cbabc46/library/src/main/java/io/github/douglasjunior/androidSimpleTooltip/SimpleTooltip.java#L632-L638

And as you can see, a default appearance `R.style.simpletooltip_default` is set to it, with these defaults:

https://github.com/douglasjunior/android-simple-tooltip/blob/21083fce4495666cf29f062b23a8e2838cbabc46/library/src/main/res/values/styles.xml#L2-L13

So to change the text size, you can define a new `R.style.simpletooltip_default` or provide a custom `contentView`.
