### ISSUE TITLE
How to descrease distances between arrow and the target view. And how to set margin for custom layout?

### ISSUE THREAD

**Issue by huutuan06** [douglasjunior/android-simple-tooltip#122]
Hello, I am using this library and got some issues, please help. 
![image](https://github.com/douglasjunior/android-simple-tooltip/assets/47626041/fc8f1c0d-b6ac-4410-b595-fdee5796b41a)

**Comment by douglasjunior** [comment]
Hi!

Everything that you can customize is here:

 https://github.com/douglasjunior/android-simple-tooltip/blob/master/sample/src/main/java/io/github/douglasjunior/androidSimpleTooltip/sample/MainActivity.java

**Comment by douglasjunior** [comment]
The limitations:

https://github.com/douglasjunior/android-simple-tooltip#known-issues
