### ISSUE TITLE
ToolTip OnClickListener

### ISSUE THREAD

**Issue by albertorusso90** [douglasjunior/android-simple-tooltip#13]
Is it possible to have an option to know if the tooltip was dismissed from clicking it? I need to know if the tooltip was dismissed from clicking it instead of from touching another element on the screen.

I tried the dismissOnOutsideTouch(false), but i need the tooltip to disappear when user does other actions, so this approach is not perfect for me.

**Comment by douglasjunior** [comment]
You could put a button in the `Tooltip`, or capture the `onClick` event in some other internal components.

``` java
            final SimpleTooltip tooltip = new SimpleTooltip.Builder(this)
                    .anchorView(v)
                    .text(getString(R.string.btn_modal_custom))
                    .gravity(Gravity.TOP)
                    .dismissOnOutsideTouch(false)
                    .dismissOnInsideTouch(false)
                    .modal(true)
                    .animated(true)
                    .animationDuration(2000)
                    .animationPadding(SimpleTooltipUtils.pxFromDp(50))
                    .contentView(R.layout.tooltip_custom, R.id.tv_text)
                    .build();

            tooltip.findViewById(R.id.btn_next).setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v2) {
                    if (tooltip.isShowing())
                        tooltip.dismiss();
                    new SimpleTooltip.Builder(v.getContext())
                            .anchorView(v)
                            .text(getString(R.string.btn_next))
                            .gravity(Gravity.BOTTOM)
                            .build()
                            .show();
                }
            });

            tooltip.show();
```

In this example is capturing the event for the `button`, but it could be the `layout`. 

``` java
tooltip.findViewById(R.id.my_root_layout).setOnClickListener(new View.OnClickListener() {
    @Override
    public void onClick(View v2) {
    // do something ...
    } 
});

```

This would be useful?

**Comment by albertorusso90** [comment]
yes thank you. Thats exactly what i was looking for. Very useful

**Comment by preyesm** [comment]
@douglasjunior hi, the tooltip library is just too good and simple to use. Thanks:)

I am using singleton instance of this tooltip to show only one at a time in my application. 

I was looking to show the other tool tip when the current under display is being dismiss. But the onDismisslistener isnt working as expected. 

I just found this custom view layout click listener, but wanted to know why is the DismissListener not working as expected. 

My code is as follows:

```java
if (GlobalToolTipVIew.getToolTipBuilder() != null) {
                   GlobalToolTipVIew.getToolTipBuilder().onShowListener(new SimpleTooltip.OnShowListener() {
                        @Override
                        public void onShow(SimpleTooltip tooltip) {
                            System.out.println("showing tooltip");
                        }
                    });
                    GlobalToolTipVIew.getToolTipBuilder().onDismissListener(new SimpleTooltip.OnDismissListener() {
                        @Override
                        public void onDismiss(SimpleTooltip tooltip) {
                            System.out.println("inside dismiss listener");
                            if (counter < toolTips.size()) {
                                System.out.println("inside dismiss listener");
                                if(!ToolTipCacheUtils.getStatusForName(toolTips.get(counter).getName())) {
                                    showToolTip( toolTips.get(counter).getV(), toolTips.get(counter).getMessage(), toolTips.get(counter).getGravity());
                                    ToolTipCacheUtils.setStatusForName(toolTips.get(counter).getName());
                                }
                                counter++;
                            }
                        }
                    });
                }
        }
```

**Comment by douglasjunior** [comment]
The `OnDismissListener` is just called by the `onDismiss` of the `PopupWindow`. I just forward the event. See [this line](https://github.com/douglasjunior/android-simple-tooltip/blob/5ff95363b93b1c62b970355cdcadbb4df6680cb6/library/src/main/java/io/github/douglasjunior/androidSimpleTooltip/SimpleTooltip.java#L335).

His behavior will depend on how you are controlling the tooltips.

In the past, I've implemented a manager similar to yours that showed the tooltips in sequence. See [this gist](https://gist.github.com/douglasjunior/43a024c67c54fe1c9c848f88b1b65d89).

_Please, if it does not solve your problem, create a new issue._ 😄
