### ISSUE TITLE
Text size change

### ISSUE THREAD

**Issue by S1LL** [douglasjunior/android-simple-tooltip#17]
Hey,
awesome library! Is there a way to change text size inside tooltip without using custom layout?

Thanks, have a nice day.

**Comment by douglasjunior** [comment]
Today, you can change the style attributes by creating a custom style named `simpletooltip_default`.

``` xml
    <style name="simpletooltip_default" parent="@android:style/TextAppearance">
        <item name="android:textSize">50sp</item>
    </style>
```

This will override the https://github.com/douglasjunior/android-simple-tooltip/blob/master/library/src/main/res/values/styles.xml

🎉

**Comment by S1LL** [comment]
awesome, thanks

**Comment by rakaadinugroho** [comment]
just changed from Style
`<style name="simpletooltip_default" parent="@android:style/TextAppearance.Small" />`
if you want to change to small text
