### ISSUE TITLE
tooltip on MenuItem

### ISSUE THREAD

**Issue by qbait** [douglasjunior/android-simple-tooltip#20]
Hey, is there a way to show a tooltip on MenuItem?

**Comment by douglasjunior** [comment]
Hmmm, I didnt tried it yet.

You can get an View from the MenuItem?

**Comment by douglasjunior** [comment]
See if [this](http://stackoverflow.com/questions/13344616/get-the-view-from-the-action-bar-menu-item) or [this](http://stackoverflow.com/questions/8614293/android-get-view-reference-to-a-menu-item) helps you.

**Comment by douglasjunior** [comment]
@qbait any progress?
