### ISSUE TITLE
Tooltip does not disappear on back press in Fragments

### ISSUE THREAD

**Issue by harshsharma94** [douglasjunior/android-simple-tooltip#21]
Is there a way to capture Key Events in Tooltip Builder. Setting Modal true doesn't help either.

**Comment by douglasjunior** [comment]
Tooltip is based on [PopupWindow](https://developer.android.com/reference/android/widget/PopupWindow.html), so it dont capture key pressed automatically.

You have to maintain a reference for Tooltip and override `onBackPressed()`.

``` java
@Override
public void onBackPressed() {
    if (tooltip != null && tooltip.isShowing()) {
        tooltip.dismiss();
    } else {
        super.onBackPressed();
    }
}
```
