### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by SimonSun7** [douglasjunior/android-simple-tooltip#27]
Hi
What should I do, if the user srcolls the layout with the view inside that is used to show a simple tooltip?

**Comment by douglasjunior** [comment]
Hi @SimonSun7 

If the user scrolls the layout behind the tooltip, you should close the tooltip. However, if you want the user not to be able to scroll the layout while the tooltip is open, set `modal=true` [like this](https://github.com/douglasjunior/android-simple-tooltip/blob/35c71dd89dbb05eda5a58338bf856be012d029c3/sample/src/main/java/io/github/douglasjunior/androidSimpleTooltip/sample/MainActivity.java#L156).

**Comment by SimonSun7** [comment]
Of course, modal!
Why I didn't think about it!?
Thank you so much...

**Comment by douglasjunior** [comment]
You're welcome. 😄
