### ISSUE TITLE
Is it compatible with Dialog.MinWidth themes?

### ISSUE THREAD

**Issue by kurtiago** [douglasjunior/android-simple-tooltip#28]
Hi, thanks for this cool library. I have tried it in my app which uses Theme.AppCompat.Dialog.MinWidth, the app only covers 1/3 of the screen. When the tooltip triggers, it stretches the layout to fullscreen, once the tip is dismissed the layout goes back to normal.

I've tried many different ways to solve this, without success.  I would appreciate if you could help me out.
Thanks in advance!

**Comment by douglasjunior** [comment]
Hi @kurtiago ,

SimpleTooltip insert a View with FILL_PARENT in RootLayout to capture the outside click. Is the same View that is used to create overlay efect.

Maybe this View is stretching the layout to full screen. Could you provide an example of this problem so that I can evaluate? I'd like to know how you're working with your layout.

**Comment by kurtiago** [comment]
Hi again, thanks for the quick reply.
 As I thought, the FILL_PARENT is forcing the screen to take all space available. I disabled the overlay effect, thinking this would get rid of the "invisible" View. But I forgot about the click capturing. So the View is still there. 

Just by looking my layout you can have a pretty good idea:
![screenshot_2016-12-01-22-48-57](https://cloud.githubusercontent.com/assets/9596872/20819303/9c5f0490-b81a-11e6-8f86-4a629a677558.png)

When I call SimpleTooltip:
![screenshot_2016-12-01-22-49-06](https://cloud.githubusercontent.com/assets/9596872/20819323/b9c10164-b81a-11e6-97d4-388737cf4517.png)

Do you think there is any way to work around this? Otherwise I need to create my own tour implement (which I don't think I'm able of). I tested your library in my full screen apps and it looks great! I wish I could use for this app as well.

Thanks!

**Comment by douglasjunior** [comment]
That's what I thought.

I confess that I've never worked with this type of layout, but it's really cool.

I think I can get a solution. Could you provide some example app? If you prefer, make a fork of this project and modify the Sample Project.

**Comment by kurtiago** [comment]
Thanks a lot, Douglas. I've decided to fork your code for educational purposes. In fact, I managed to get rid of the overlay so now the screen looks perfect! Now I only have to replace the overlay touch listener for some view listener so the user can dismiss it by either clicking the tooltip or clicking the showcased view.

I appreciate a lot your support. Take care!

**Comment by douglasjunior** [comment]
Glad it was solved. It was basically what I thought of doing. I think it's an important feature for the library. I'll look at this later.

Thanks.
