### ISSUE TITLE
Not getting any tooltip in ListView header's element in Fragment

### ISSUE THREAD

**Issue by javiyavandan** [douglasjunior/android-simple-tooltip#29]
i have used fragment and in fragment i have used ListView and in ListView i have added header and in header i have two element TextView and ImageView and i want to put tooltip in both ImageView and TextView 
i have tried below code to show tooltip. but i'm not able to show it in header part of ListView.
so Please let me know if any suggestion..thanks

```java
 new SimpleTooltip.Builder(getActivity())
                .anchorView(headerView.findViewById(R.id.textView_headerView))
                .text("Test")
                .gravity(Gravity.TOP)
                .animated(true)
                .transparentOverlay(false)
                .build()
                .show();
```

**Comment by douglasjunior** [comment]
Hi @javiyavandan, thanks for reporting!

I have not tested this situation, I will do some tests and I will return soon.

**Comment by douglasjunior** [comment]
@javiyavandan I added a sample using Fragment + ListView + Header in this branch: [fragment-listview-header](https://github.com/douglasjunior/android-simple-tooltip/tree/fragment-listview-header)

In my tests everything seems to work fine.

![screenshot_20161231-201701](https://cloud.githubusercontent.com/assets/1512341/21579447/cb03da30-cf96-11e6-8e72-41e9612a8e2c.png)

Let me know if you need any help. 😃 

_(Sorry, I clicked to close unintentionally.)_

**Comment by douglasjunior** [comment]
If you want, be free to reopen the issue.

**Comment by javiyavandan** [comment]
ok Done thanks a lot
