### ISSUE TITLE
view perform click called after dismissal

### ISSUE THREAD

**Issue by klifa90** [douglasjunior/android-simple-tooltip#33]
Is there any particular reason why v.performClick() is called at the beginning instead of the end of the method?

The reason is that I (i imagine many face the same) want to use the click of the view to also toggle the tooltip state. 

```
imgViewInfoIcon.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (mSimpleTooltip!=null && mSimpleTooltip.isShowing())
                {
                    mSimpleTooltip.dismiss();
                }else{
                mSimpleTooltip = new SimpleTooltip.Builder(getActivity())
                        .anchorView(imgViewInfoIcon)
                        .text(mFormDescription)
                        .gravity(Gravity.BOTTOM)
                        .animated(false)
                        .showArrow(true)
                        .transparentOverlay(false)
                        .build();
                    mSimpleTooltip.show();
                }
            }
        });
```

This should work. The thing is that the tooltip is being dismissed BEFORE the onclick is dispatched so it will always be false. 

What happens now is that if i click on my info icon, then the tooltip displays. If i tap it again (which most users do, to close it) then the tooltip closes and opens in a flash.

**Comment by douglasjunior** [comment]
You can try to set `modal=true`, [like this](https://github.com/douglasjunior/android-simple-tooltip/blob/35c71dd89dbb05eda5a58338bf856be012d029c3/sample/src/main/java/io/github/douglasjunior/androidSimpleTooltip/sample/MainActivity.java#L156).

If `modal=true` the Tooltip handle the touch event and prevent that event from reaching the view in background.

**Comment by klifa90** [comment]
That´s actually the solution I was looking for. Sorry I didn't looked enough for the modal option. Thanks!

**Comment by douglasjunior** [comment]
You're welcome 😄
