### ISSUE TITLE
Clickable view

### ISSUE THREAD

**Issue by DavidGalvis** [douglasjunior/android-simple-tooltip#38]
can be element inner anchorView  clickable with .modal(true) ?, I couldn't. I want to click only inner anchorView element.

**Comment by douglasjunior** [comment]
Unfortunately, not now. The modal mode enable touch capture in the OverlayView. This OverlayView covers 100% of the screen. 

What can be implemented in library is a listener to capture touch event. Then allow get the touch position and delegate the event to Views in background.

I can take a look at the weekend. If you have a suggestion, please feel free to submit a pull request. 😄

**Comment by DavidGalvis** [comment]
Yes I have a suggestion, I can work on this at the weekend too and if it works, i will send you a pull request. I'm happy to help you.

**Comment by 10K-with-AI-Enterprise-Edition** [comment]
Did you happen to make it work?

**Comment by douglasjunior** [comment]
Sorry, not yet. I'm very busy right now.

**Comment by HarshLathigara1** [comment]
i have used setContentView
And I wanrt to add conclick in chlld element
Onclick listner not working

**Comment by fiveSpeedMazdarati** [comment]
I'm having a similar issue. I'm using this to display a message, and have a requirement to only dismiss the tooltip if the user touches on a certain icon inside of the tooltip.
