### ISSUE TITLE
Why not give credit, keep license and not remove other attributes?

### ISSUE THREAD

**Issue by JoaquimLey** [douglasjunior/android-simple-tooltip#41]
- This **lib** is clearly a _fork_ of https://github.com/sephiroth74/android-target-tooltip, I get it it doesn't have much support. But you should give credit when it's due. It's open source code why try to pass it as your own, don't take this in the wrong way, I'm just curious on how you stand on this 🤔.

Also, you removed the ability to customize some stuff that was present on the original, other then that great job 💪.

**Comment by douglasjunior** [comment]
No, it is not a copy and no line of code has been copied. But I'm curious, what made you think that this is a copy? I hope you can argue about this as it is a serious accusation for me.

I respect the license policies and [I insist that must be respected](https://github.com/ViHtarb/Tooltip/issues/27).

About the `android-target-tooltip`, when I needed a tooltip I got to use it and [tried to contribute with the project](https://github.com/sephiroth74/android-target-tooltip/pulls?q=is%3Apr+author%3Adouglasjunior+is%3Aclosed), but the owner did not seem interested. Then I start to create the `android-simple-tooltip` without taking advantage of any line of code.

You do not have to be an expert to see this, as the `android-target-tooltop` implements a new [custom view](https://github.com/sephiroth74/android-target-tooltip/blob/1f1ee71a22efd620f398e3416fdb33a4c768bc23/library/src/main/java/it/sephiroth/android/library/tooltip/Tooltip.java#L234). While in the `android-simple-tooltip` I [use the `PopupWindow`](https://github.com/douglasjunior/android-simple-tooltip/blob/11255b06884b81973d61399c495983ec49380733/library/src/main/java/io/github/douglasjunior/androidSimpleTooltip/SimpleTooltip.java#L89).

I hope you can justify yourself about that.

**Comment by JoaquimLey** [comment]
I'm glad you replied. Well, like I said don't take it the wrong way, I was indeed curious how you stand, it really sucks well people take your code and pass it their own, I found you lib quite the same as the other. Anyway good job 💪.

**Comment by douglasjunior** [comment]
For me, github is a serious thing. The most important thing is not to make a charge about what you think.
