### ISSUE TITLE
Rare crash in OverlayView

### ISSUE THREAD

**Issue by rasmusohrstig** [douglasjunior/android-simple-tooltip#42]
I have logged some crashes from users in Crashlytics that I am unable to reproduce myself. It seems like the Bitmap in OverlayView is sometimes null when it is passed to Canvas.drawBitmap().

Again, I have no idea how to reproduce this. We've had 28 crashes from showing the tooltip about 70,000 times, so it happens about 0.005% of the time. Could be a race condition. 

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference
       at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1270)
       at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:257)
       at android.graphics.Canvas.drawBitmap(Canvas.java:1336)
       at io.github.douglasjunior.androidSimpleTooltip.OverlayView.dispatchDraw(OverlayView.java:70)
       at android.view.View.draw(View.java:17235)
       at android.view.View.updateDisplayListIfDirty(View.java:16197)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3758)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3738)
       at android.view.View.updateDisplayListIfDirty(View.java:16160)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:676)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:682)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:796)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2989)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2783)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2374)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1364)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6757)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:923)
       at android.view.Choreographer.doCallbacks(Choreographer.java:735)
       at android.view.Choreographer.doFrame(Choreographer.java:667)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:909)
       at android.os.Handler.handleCallback(Handler.java:755)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6524)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
```

The tooltip is created like so:

```
myTooltip = new SimpleTooltip.Builder(this)
                .anchorView(myButton)
                .text(getResources().getString(R.string.MY_TOOLTIP_TEXT))
                .textColor(getResources().getColor(R.color.white))
                .backgroundColor(getResources().getColor(R.color.my_color))
                .arrowColor(getResources().getColor(R.color.my_color))
                .gravity(Gravity.TOP)
                .animated(true)
                .transparentOverlay(false)
                .onDismissListener(new SimpleTooltip.OnDismissListener() {
                    @Override
                    public void onDismiss(SimpleTooltip tooltip) {
                        lockScrollView = false;
                    }
                })
                .build();
```

The lockScrollView variable is a boolean that prevents an enclosing ScrollView from scrolling. It's probably unrelated to the crash, but here is how that works:

```
scrollView = (ObservableScrollView) findViewById(R.id.scrollview);
        scrollView.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View v, MotionEvent event) {
                return lockScrollView;
            }
        });
```

**Comment by milos192** [comment]
I was getting this all the time when I was showing a Popup in onCreate() and doing rotations on a tablet. Moving the showing to onStart() fixed the issue but it wasn't feasible to me. Maybe try to reproduce it like that?

**Comment by rasmusohrstig** [comment]
Thanks. That sounds like a good idea.

The Tooltip is currently triggered by a callback from another thread that could happen before onStart() if the device is running slow.

I'll get back with the results once we've shipped the next version.

**Comment by douglasjunior** [comment]
@rasmusohrstig first: thanks for the feedback 😄 

In addition to what @milos192 said, this exception may be caused when the app goes idle and is killed by the Android. What version of the library are you using?

Anyway, I'll add a check at this point.

_@milos192 thanks for the support, appreciate that._

**Comment by milos192** [comment]
No problem. I just wanted to mention that I actually tried fixing this on
my fork, but to no avail. I instantiated the Bitmap every time,
unconditionally, but I still ended up with the same exception. It was very
weird.

**Comment by douglasjunior** [comment]
I think this is a false exception, because while the [`bitmap = null`](https://github.com/douglasjunior/android-simple-tooltip/blob/11255b06884b81973d61399c495983ec49380733/library/src/main/java/io/github/douglasjunior/androidSimpleTooltip/OverlayView.java#L52), the [`invalidated = true`](https://github.com/douglasjunior/android-simple-tooltip/blob/11255b06884b81973d61399c495983ec49380733/library/src/main/java/io/github/douglasjunior/androidSimpleTooltip/OverlayView.java#L54). 

Both are changed at the same time in the [`createWindowFrame`](https://github.com/douglasjunior/android-simple-tooltip/blob/11255b06884b81973d61399c495983ec49380733/library/src/main/java/io/github/douglasjunior/androidSimpleTooltip/OverlayView.java#L73) method. So it is impossible for the `bitmap` to get `null` on [`line 70`](https://github.com/douglasjunior/android-simple-tooltip/blob/11255b06884b81973d61399c495983ec49380733/library/src/main/java/io/github/douglasjunior/androidSimpleTooltip/OverlayView.java#L70).

Anyway, I created a new branch and changed this:
```java
    @Override
    protected void dispatchDraw(Canvas canvas) {
        if (invalidated)
            createWindowFrame();

        canvas.drawBitmap(bitmap, 0, 0, null);
    }
```

For this:
```java
    @Override
    protected void dispatchDraw(Canvas canvas) {
        if (invalidated || bitmap == null || bitmap.isRecycled())
            createWindowFrame();

        canvas.drawBitmap(bitmap, 0, 0, null);
    }
```

Prease, try this version:
```gradle
dependencies {
    // ...
    compile ('com.github.douglasjunior:android-simple-tooltip:issue-42-SNAPSHOT') {
        changing = true // Gradle will then check for updates every 24 hours
    }
}
```

**Comment by rasmusohrstig** [comment]
Thanks. 

I have not seen the bug happen myself, so I can't say for sure that it is real. The thing that stands out in the Crashytics reports is that 77% report the app not in focus.

I guess there might be some framework sorcery going on that causes the bitmap to be set to null through reflection before the process is killed.

**Comment by douglasjunior** [comment]
So maybe the best solution would be:
```java
    @Override
    protected void dispatchDraw(Canvas canvas) {
        if (invalidated)
            createWindowFrame();
        
        Bitmap bitmap = this.bitmap;
        if (bitmap != null && !bitmap.isRecycled())
            canvas.drawBitmap(bitmap, 0, 0, null);
    }
```

If it is `null` it will only be ignored.

**Comment by douglasjunior** [comment]
@milos192 , @rasmusohrstig  Guys, can I release this fix, how are the crash reports?

**Comment by milos192** [comment]
I have moved away from using the OverlayView. I am using WindowManager
parameters instead. So I can't help with data here, sorry. :/

**Comment by rasmusohrstig** [comment]
We've been rolling out a new version of our app this week, using the same 0.2.0 version of Simple tooltips. So far the crashes appear to be gone, thanks to @milos192 tip about not showing the tooltip in onCreate(). It is still to early to tell with certainty. I'll know sometime next week for sure.

I have unfortunately not been able to test the code fix. I am still unable to reproduce the crash on my own using the original code, so there is no way to tell if it makes a difference.

Again, not showing the tooltip in onCreate() seems to solve the problem. It makes sense from an Android framework point of view since the onCreate() method is for creating objects, whicle onStart() is for starting/showing the stuff that you created in onCreate().

**Comment by douglasjunior** [comment]
Ok, no problem, thank you all.
