### ISSUE TITLE
inside conentview element make clickable   

### ISSUE THREAD

**Issue by yashshekhada** [douglasjunior/android-simple-tooltip#43]
hello sir 

      i have a problem.
      can i make inside contentview layout controls are clickable
like this
  
![capture](https://cloud.githubusercontent.com/assets/28475432/26813818/9bec80b6-4a9e-11e7-9f2d-dcf106575305.PNG)

in this are calculator, can be possible

**Comment by douglasjunior** [comment]
In version `0.2.0` was added the option `focusable(true)`. Have you tried with this option?

See the [example code](https://github.com/douglasjunior/android-simple-tooltip/blob/5ff95363b93b1c62b970355cdcadbb4df6680cb6/sample/src/main/java/io/github/douglasjunior/androidSimpleTooltip/sample/MainActivity.java#L175).

**Comment by yashshekhada** [comment]
Thank sir

Sent from Mail for Windows 10
