### ISSUE TITLE
.arrowDrawable()

### ISSUE THREAD

**Issue by yashshekhada** [douglasjunior/android-simple-tooltip#44]
how to set arrow as drawable layout

**Comment by douglasjunior** [comment]
Hi!

[ArrowDrawable](https://github.com/douglasjunior/android-simple-tooltip/blob/master/library/src/main/java/io/github/douglasjunior/androidSimpleTooltip/ArrowDrawable.java) is the default `Drawable` used by Tooltip to create the arrow, the options are available in `Builder`.

You can set a new drawable (like an image) or customize with `Builder` options.

```java
builder.arrowDrawable(drawable/intRes);
```
Or
```java
builder.showArrow(boolean);
builder.arrowColor(int);
builder.arrowHeight(float);
builder.arrowWidth(float);
```
