### ISSUE TITLE
Listview Item click listner don't work

### ISSUE THREAD

**Issue by harshipatelb** [douglasjunior/android-simple-tooltip#45]
tooltip having listview and i want to item click listner of listvew not work

This library use==>**compile 'com.github.douglasjunior:android-simple-tooltip:0.2.0'**

```java
Listview lv=(Listview)**tooltip**.findViewById(R.id.lv);
lv.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {

                    Toast.makeText(MainActivity.this,  "hello" , Toast.LENGTH_SHORT).show();

            }
});
```

**Comment by harshipatelb** [comment]
plz ans me

**Comment by douglasjunior** [comment]
Hello, sorry, you closed the issue and I thought it was already resolved.

Have you tried to enable focus on the Tooltip?
```java
tooltipBuilder.focusable(true);
```

Please tell me all the properties you are setting to create the Tooltip so I can reproduce the problem.

**Comment by harshipatelb** [comment]
in my project on this functionality is also true 
tooltipBuilder.focusable(true);
that not working so plz give me other solution with example

**Comment by douglasjunior** [comment]
The only option that could block the click on the internal components is the `focusable`.

Have you checked the [sample project](https://github.com/douglasjunior/android-simple-tooltip/blob/a5f99e963f0de5e9500627c9e2dc743df8fbb4b7/sample/src/main/java/io/github/douglasjunior/androidSimpleTooltip/sample/MainActivity.java)? Here is an [example](https://github.com/douglasjunior/android-simple-tooltip/blob/a5f99e963f0de5e9500627c9e2dc743df8fbb4b7/sample/src/main/java/io/github/douglasjunior/androidSimpleTooltip/sample/MainActivity.java#L164-L194) of using an EditText within the Tooltip with the click working.

Edit the sample project and replace the EditText with your ListView. If it does not work, paste the source code you used here.

**Comment by harshipatelb** [comment]
this code worked but in my project i have use  a list view and i am trying to onitemclick listener  so can u have any idea how to call this 



btn_multi.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                final SimpleTooltip tooltip = new SimpleTooltip.Builder(MainActivity.this)
                        .anchorView(v)
                        .text("Aggregrators")
                        .gravity(Gravity.BOTTOM)
                        .dismissOnOutsideTouch(false)
                        .dismissOnInsideTouch(false)
                        .modal(true)
                        .contentView(R.layout.home_activity_header_refine_tooltip, R.id.tv_refine_header)
                        .focusable(true)
                        .build();
                Refine_list = new ArrayList<Refine_Aggregrator_ModelList>();
                lv_home_menu_aggregrators = (ListView) tooltip.findViewById(R.id.lv_home_menu_aggregrators);

                Refine_list.add(new Refine_Aggregrator_ModelList("Gift Ideas"));
                Refine_list.add(new Refine_Aggregrator_ModelList("New Products"));
                Refine_list.add(new Refine_Aggregrator_ModelList("Design Products"));
                Refine_list.add(new Refine_Aggregrator_ModelList("Spring-Summer-2016"));
                Refine_list.add(new Refine_Aggregrator_ModelList("Carsaie 2017"));
                Refine_list.add(new Refine_Aggregrator_ModelList("Best Saller cliente selezionato"));
              

                Refine_Aggregrator_Adapter adapter = new Refine_Aggregrator_Adapter(getApplicationContext(), R.layout.raw_refine_agrregrator, Refine_list);
                lv_home_menu_aggregrators.setAdapter(adapter);
                ((ListView) tooltip.findViewById(R.id.lv_home_menu_aggregrators)).setOnItemClickListener(new AdapterView.OnItemClickListener() {
                    @Override
                    public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                        Toast.makeText(MainActivity.this, "Not Work this", Toast.LENGTH_SHORT).show();
                    }
                });
                tooltip.show();
            }
        });
Listview data properly get but Itemclick Listner to get position but does not work

**Comment by harshipatelb** [comment]
plz answer me

**Comment by douglasjunior** [comment]
Did you do make the tests that I suggested?

There are a multitude of variables that may be blocking the click of the item, it may be setting in your contentView, or even in the layout of the adapter's item. If necessary, create a clean project to simulate the problem.

I'm pretty sure it's not the Tooltip that's blocking the click. Make a test, add a Button to your layout and capture the click event of the button.

```java
            tooltip.findViewById(R.id.my_button).setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v2) {
                    Toast.makeText(MainActivity.this, "Its working!", Toast.LENGTH_SHORT).show();
                }
            });
```

If the button works, the problem is with your layout.

**Comment by harshipatelb** [comment]
ya that's true and it worked ,but i want to set on item click event.

**Comment by douglasjunior** [comment]
The problem is in the layout of your ListView or Adapter. First try to make it work outside of the Tooltip (create an activity for testing), it is easier to find problems.
