### ISSUE TITLE
DialogFragment resize when tooltip shown

### ISSUE THREAD

**Issue by nicomazz** [douglasjunior/android-simple-tooltip#46]
When I display a tooltip inside a DialogFragment, the dialog resize itself. How can I prevent it?

Without the tooltip:
![screenshot_1500030219](https://user-images.githubusercontent.com/4215054/28209895-f3c936b2-6894-11e7-8ee6-967bb3344117.png)
With the tooltip:
![screenshot_1500030231](https://user-images.githubusercontent.com/4215054/28209896-f3d351b0-6894-11e7-8aa9-55478914c9ce.png)

**Comment by douglasjunior** [comment]
Hi, thanks for the feedback!

I think this is related to #28, but I cant replicate the problem here. Could you provide a minimal project sample?

This probably happens because Tooltip creates a background view that fill your parent. This view is used to capture the "background touch" and make the overlay effect. But with common Dialog this problem does not happen.

**Comment by nicomazz** [comment]
Thanks for the quick response!

I've resolved by manually setting the view size like in the sample:
``` java
WindowManager.LayoutParams lp = new WindowManager.LayoutParams();
lp.copyFrom(dialog.getWindow().getAttributes());
lp.width = (int) SimpleTooltipUtils.pxFromDp(300);
lp.height = (int) SimpleTooltipUtils.pxFromDp(300);
dialog.getWindow().setAttributes(lp);
```

**Comment by douglasjunior** [comment]
Glad it worked, but you'll have trouble if you need a dynamic height.

**Comment by nicomazz** [comment]
True
I've made a fork of the project and added the case in the sample. Could you give it a look?

Thank you very much!

**Comment by douglasjunior** [comment]
I've made some changes to try to solve the problem.

Please try to use the version below with the option [`overlayMatchParent(false)`](https://github.com/douglasjunior/android-simple-tooltip/blob/45e1b5269830650786d467f8a43d94c685853eab/sample/src/main/java/io/github/douglasjunior/androidSimpleTooltip/sample/MainActivity.java#L233).

```gradle
dependencies {
    // ...
    compile ('com.github.douglasjunior:android-simple-tooltip:issue-46-SNAPSHOT') {
        changing = true // Gradle will then check for updates every 24 hours
    }
}
```

**Comment by nicomazz** [comment]
It works perfectly!

**Comment by douglasjunior** [comment]
One problem that still exists is if the Dialog resizes after the Tooltip is open. In this case you would need to close the Tooltip and open it again.

**Comment by douglasjunior** [comment]
Version [0.2.1](https://github.com/douglasjunior/android-simple-tooltip/releases/tag/0.2.1) has been released.
