### ISSUE TITLE
Stretching dialog and changing dialog size

### ISSUE THREAD

**Issue by saqibsoftwares** [douglasjunior/android-simple-tooltip#50]
Hi there, I'm displaying an activity as a dialog using dialog theme. It is appcompat activity. After triggered the the simple tool time, it is changing my dialog size. After triggering it, My dialog taking all the space available on screen. How can I resolve it?

**Comment by douglasjunior** [comment]
Hi, are you using version `0.2.1`?

Take a look in issue #46

**Comment by saqibsoftwares** [comment]
Thank you @douglasjunior for your quick response and guide. Yes I'm using 0.2.1. It's my bad, I should set the property `.overlayMatchParent`  to `false`. After setting it to false the problem has been resolve. To make this project great and error free I would like to mention that there are still very minor extra stretching like 15dp in my dialog which is acceptable. :)

**Comment by saqibsoftwares** [comment]
![screenshot_1501429198](https://user-images.githubusercontent.com/11803610/28754875-e2f9ff08-7567-11e7-9a5e-9270806e3f9e.png)

**Comment by douglasjunior** [comment]
This is strange, could you provide the layout XML of your Dialog and the Tooltip creation code?

**Comment by saqibsoftwares** [comment]
Sure, Please collect it from the attachments. 
[attachments.zip](https://github.com/douglasjunior/android-simple-tooltip/files/1185804/attachments.zip)

**Comment by douglasjunior** [comment]
Thanks, I'll take a look.
