### ISSUE TITLE
Way to set Text size and/or anchor via coordinates 

### ISSUE THREAD

**Issue by borisblanc** [douglasjunior/android-simple-tooltip#52]
Hey just in case I missed it can I set Text size somehow or perhaps the popup coordinates without a view anchor? Very useful library!!

thank you

**Comment by borisblanc** [comment]
ok I see this is the way to override anything text related...https://github.com/douglasjunior/android-simple-tooltip/issues/24

Any help on setting the popup coordinates without a view anchor would be great, thanks..

**Comment by borisblanc** [comment]
I guess this is the closest I can see to what I need but really I need something more granular than just gravity where I can set x and y maybe?

```java
new SimpleTooltip.Builder(this)
                    .anchorView(v.getRootView())
                    .text(R.string.btn_center)
                    .showArrow(false)
                    .gravity(Gravity.CENTER)
                    .build()
                    .show();
```

My issue is that I am drawing a small bitmap to a canvas and I need to display this along with the bitmap which is only drawn many times per second and never rendered as its own view.

**Comment by douglasjunior** [comment]
I understood your problem, sorry for the delay, I've been very busy the last few days.

Unfortunately it is not possible to display the Tooltip without an anchor view.
