### ISSUE TITLE
Arrow alignment

### ISSUE THREAD

**Issue by jzeferino** [douglasjunior/android-simple-tooltip#53]
There is any way to achieve something like this:

![screen shot 2017-08-18 at 20 42 40](https://user-images.githubusercontent.com/10722952/29475039-0420568a-8456-11e7-975f-2633b07af55c.png)

Making the arrow align right and the tooltip width match parent?

**Comment by douglasjunior** [comment]
The default view is like this. What is your difficulty?

**Comment by jzeferino** [comment]
@douglasjunior As I said. The default arrow alignment is centered. I need it to be positioned in right side.

**Comment by douglasjunior** [comment]
It will be positioned in right/left side only if the anchor is near of the screen border, and the gravity is TOP or BOTTOM. But if the anchor is in the center of the screen, the tendency is for the arrow to be centered.

**Comment by PetreaLoredana** [comment]
@jzeferino Did u find a way to move the arrow at the top right side?
