### ISSUE TITLE
margin not working / Toolbar

### ISSUE THREAD

**Issue by stern0m1** [douglasjunior/android-simple-tooltip#55]
I am trying to place the tooltip to the left of the toolbar in the actionbar (the 3 dots in the top right corner)
it covers up the 3 dots.
I tried with the margin method to push it over a bit but it doesnt do anything.
I tried the margin method with other views, just to test, and it didnt do anything easier.

```java
new SimpleTooltip.Builder(this)
           .margin(Float.valueOf(100))
                .anchorView(toolbar)
                .text("Texto do Tooltip")
                .gravity(Gravity.END)
                .animated(true)
                .transparentOverlay(true)
                .arrowColor(Color.RED)
                .margin(Float.valueOf(16))
                .arrowDirection(ArrowDrawable.RIGHT)
                .build()
                .show();
```

**Comment by douglasjunior** [comment]
Try change the `Float.valueOf(16)` to `SimpleTooltipUtils.pxFromDp(16)`.

**Comment by stern0m1** [comment]
Thanks. That helps with regular views.
I can't figure out how to anchor it to action menu, the 3 dots in the top
right corner that brings up a menu.
I was mistakenly anchoring to the "toolbar" but in reality I need to anchor
to those 3 dots.

How can I get a reference to those 3 dots? That menu is just added
automatically with the toolbar, I have not declared the menu separately.

Thanks

**Comment by douglasjunior** [comment]
Sorry, I'm not sure how.

Try something like this: https://stackoverflow.com/questions/29922995/get-toolbars-navigation-icon-view-referrence
