### ISSUE TITLE
change text style to bold.

### ISSUE THREAD

**Issue by Neha1490** [douglasjunior/android-simple-tooltip#56]
Hi

How can I change text style of text inside tooltip i.e. from normal to bold.

tooltip library version -  compile 'com.github.douglasjunior:android-simple-tooltip:0.2.1'

**Comment by douglasjunior** [comment]
There are two ways.

1. You can edit the default text style. See #17

1. You can set a custom content. See [this line](https://github.com/douglasjunior/android-simple-tooltip/blob/3a0e4d35e60798a57cb8dfdab60e65d19f8baaa4/sample/src/main/java/io/github/douglasjunior/androidSimpleTooltip/sample/MainActivity.java#L174).
