### ISSUE TITLE
Lots of crashes

### ISSUE THREAD

**Issue by 10K-with-AI-Enterprise-Edition** [douglasjunior/android-simple-tooltip#57]
I used your library in my app and we experienced lots of crashes on our users. I'll attach the logs to help you find the bugs.
In the meanwhile, sadly, I have to stop using your library.

[com.goalmeterapp.www_issue_27_crash_59C06B53006100017C3699DF86130FAF_ae35ae829cd511e78d4a56847afe9799_0_v2.txt](https://github.com/douglasjunior/android-simple-tooltip/files/1312750/com.goalmeterapp.www_issue_27_crash_59C06B53006100017C3699DF86130FAF_ae35ae829cd511e78d4a56847afe9799_0_v2.txt)

**Comment by douglasjunior** [comment]
Apparently the problem is in the way you open the tooltip.

The tooltip is a PopupWindow, and just like the Dialogs, you have to take some care.

Take a look at items 1 and 2 of [known issues](https://github.com/douglasjunior/android-simple-tooltip#known-issues).
