### ISSUE TITLE
Programmatically created content

### ISSUE THREAD

**Issue by justbittin** [douglasjunior/android-simple-tooltip#58]
I have successfully integrated your library as a plugin for DroidScript.

My question/problem is content (all content) is created dynamically.   So, there are no resource IDs.

I can pass a object into the plugin (for example a LinearLayout) and want to use this inside the tooltip.

Can you direct me to a way to do this, even if it means changing source.

Thank you for this library!

**Comment by douglasjunior** [comment]
You can use something like this:

```java
            TextView textView = null;
            textView.setText("Yout text here");

            LinearLayout layout = null;
            layout.addView(textView);
            layout.addView(otherView);
            
            final SimpleTooltip tooltip = new SimpleTooltip.Builder(this)
                    .anchorView(v)
                    .gravity(Gravity.TOP)
                    .dismissOnOutsideTouch(false)
                    .dismissOnInsideTouch(false)
                    .modal(true)
                    .animated(true)
                    .contentView(layout, 0)
                    .focusable(true)
                    .build();

            tooltip.show();
```

**Comment by justbittin** [comment]
Thank you for your quick reply.  It works perfectly, thank you for your help.
