### ISSUE TITLE
dismiss tooltip without any click

### ISSUE THREAD

**Issue by Neha1490** [douglasjunior/android-simple-tooltip#59]
I am showing tooltip on menu item in fragment. I want it to show only when some specific menu item (say menu item A) is visible.

If  menu item (A) is not visible I want it to dismiss without any click event.

This is my code-
if(item_search_map.isVisible()) {
      
                    final View menuItemView = getActivity().findViewById(R.id.item_search_map);
                    tooltip = new SimpleTooltip.Builder(getActivity());
                   // new SimpleTooltip.Builder(getActivity())
                    tooltip .anchorView(menuItemView)
                            .margin(R.dimen.simpletooltip_margin)
                            .text("See,travellers \n around you")
                            .textColor(Color.parseColor("#FFFFFF"))
                            .gravity(Gravity.START)
                            .backgroundColor(Color.parseColor("#B3555555"))
                            .dismissOnOutsideTouch(false)
                            .dismissOnInsideTouch(false)
                            .transparentOverlay(true)
                            .arrowColor(Color.parseColor("#B3555555"))
                            .build()
                            .show();
            } else {
            Log.d("else","dismiss");
            tooltip.onDismissListener(new SimpleTooltip.OnDismissListener() {
                @Override
                public void onDismiss(SimpleTooltip tooltip) {
                    tooltip.dismiss();
                }
            });
        }

**Comment by douglasjunior** [comment]
> If menu item (A) is not visible I want it to dismiss without any click event.

You should call `tooltip.dismiss()` when the item is no longer visible. What makes the item visible or not, is it a scrolling?

**Comment by Neha1490** [comment]
It is not allowing me to use tooltip.dismiss() directly. I am getting some error if I am trying to use it directly, so I have used it as I have described above.

No,It is not scrolling.

**Comment by douglasjunior** [comment]
Which error? Give more details.

**Comment by Neha1490** [comment]
tooltip.dismiss(); - cannot resolve method dismiss.

**Comment by hades-6** [comment]
you need to attach your listener when you build. @Neha1490 
```
new SimpleTooltip.Builder(getActivity());
.anchorView(menuItemView)
                .margin(R.dimen.simpletooltip_margin)
                .text("See,travellers \n around you")
                .textColor(Color.parseColor("#FFFFFF"))
                .gravity(Gravity.START)
                .backgroundColor(Color.parseColor("#B3555555"))
                .dismissOnOutsideTouch(false)
                .dismissOnInsideTouch(false)
                .transparentOverlay(true)
                .arrowColor(Color.parseColor("#B3555555"))
                .onDismissListener(new SimpleTooltip.OnDismissListener() {
                    @Override
                    public void onDismiss(SimpleTooltip tooltip) {
                        tooltip.dismiss();
                    }
                })
                .build()
                .show();
```

**Comment by hades-6** [comment]
Also you can use,
```
.dismissOnInsideTouch(false)
.dismissOnOutsideTouch(true)
```
to tweak the dismiss.

**Comment by Neha1490** [comment]
@hades-6 
Thanks for your response.
I have tried this.Its working fine but my requirement is something else. I want it to dismiss by itself at toolbar if some menu item is not visible.

**Comment by douglasjunior** [comment]
> tooltip.dismiss(); - cannot resolve method dismiss.

Make sure you're calling the `dismiss()` on the `Tooltip` object, not on the `Builder`.

```java
SimpleTooltip.Builder builder = new SimpleTooltip.Builder(getActivity());
builder.anchorView(menuItemView)
       .margin(R.dimen.simpletooltip_margin)
       .text("See,travellers \n around you")
       .textColor(Color.parseColor("#FFFFFF"))
       .gravity(Gravity.START)
       .backgroundColor(Color.parseColor("#B3555555"))
       .dismissOnOutsideTouch(false)
       .dismissOnInsideTouch(false)
       .transparentOverlay(true)
       .arrowColor(Color.parseColor("#B3555555"));

SimpleTooltip tooltip = builder.build();
```

Now when I want to close the Tooltip just do:

```java
tooltip.dismiss();
```

**Comment by desaibijon** [comment]
Hi @douglasjunior,

I have a similar kind of problem, I want to close my tooltip after 4 seconds, but I am not quite able to do that.

Below is my code:


```   
SimpleToolTip simpleToolTip;
simpleToolTip = new SimpleTooltip.Builder(getContext())
        .anchorView(binding.toolTipAnchorView)
        .contentView(R.layout.tooltip_layout, R.id.tooltip_text)
        .text(R.string.tool_tip_add_sharing_text)
        .gravity(Gravity.TOP)
        .transparentOverlay(true)
        .build();
simpleToolTip.show();

new Handler.postDelayed(
    new Runnable() {
        @Override
        if(simpleToolTip.isShowing()) {
            simpleToolTi[p.dismiss();
        }
    }, 4000);
```

What happens here is, dismiss() is called the first time, but the tooltip does not actually hide from the screen.
How I know dismiss() is getting called is because the thread runs 3 more times and isShowing() returns false after the 1st time.

Please let me know the response at your earliest.

Thanks.

**Comment by douglasjunior** [comment]
Answered in #62

**Comment by shylendramadda** [comment]
As @douglasjunior answered it's working fine for me.

```
final SimpleTooltip tooltip = new SimpleTooltip.Builder(this)
.anchorView(v)
.text("your text")
.gravity(Gravity.TOP)
.animated(true)
.transparentOverlay(true)
.build();
tooltip.show();
```

```
mHandler.postDelayed(new Runnable() {
@override
public void run() {
tooltip.dismiss();
}
}, 3000);
```
