### ISSUE TITLE
Click outside of modal window closes modal

### ISSUE THREAD

**Issue by Matho** [douglasjunior/android-simple-tooltip#60]
Hi

I'm trying your sample at commit 3a0e4d35e60798a57cb8dfdab60e65d19f8baaa4 with this settings: https://github.com/douglasjunior/android-simple-tooltip/blob/3a0e4d35e60798a57cb8dfdab60e65d19f8baaa4/sample/src/main/java/io/github/douglasjunior/androidSimpleTooltip/sample/MainActivity.java#L164-L194 It seems like dismissOnOutsideTouch do not work properly, when I click below the "modal custom" button, the modal popup disapear. I expected, it will stay visible. Thanks. 
![bug](https://user-images.githubusercontent.com/856220/31879174-daf25334-b7dc-11e7-9765-98c643fd0f4c.png)

**Comment by douglasjunior** [comment]
Hi, thanks for reporting.

Please, try again with this version: 

```gradle
    compile('com.github.douglasjunior:android-simple-tooltip:issue-60-SNAPSHOT') {
        changing = true // Gradle will then check for updates every 24 hours
    }
```

**Comment by Matho** [comment]
Thanks for your fix, it is working fine now.
