### ISSUE TITLE
toolTip.dismiss() does not dismiss/hide the tooltip.

### ISSUE THREAD

**Issue by desaibijon** [douglasjunior/android-simple-tooltip#62]
Hi @douglasjunior,

I have a similar kind of problem, I want to close my tooltip after 4 seconds, but I am not quite able to do that.

Below is my code:

```   
SimpleToolTip simpleToolTip;
simpleToolTip = new SimpleTooltip.Builder(getContext())
        .anchorView(binding.toolTipAnchorView)
        .contentView(R.layout.tooltip_layout, R.id.tooltip_text)
        .text(R.string.tool_tip_add_sharing_text)
        .gravity(Gravity.TOP)
        .transparentOverlay(true)
        .build();
simpleToolTip.show();

new Handler.postDelayed(
    new Runnable() {
        @Override
        if(simpleToolTip.isShowing()) {
            simpleToolTi[p.dismiss();
        }
    }, 4000);
```

What happens here is, dismiss() is called the first time, but the tooltip does not actually hide from the screen.
How I know dismiss() is getting called is because the thread runs 3 more times and isShowing() returns false after the 1st time.

Please let me know the response at your earliest.

Thanks.

**Comment by douglasjunior** [comment]
I created a example [here](https://github.com/douglasjunior/android-simple-tooltip/blob/9de6a36dc66ff8d3f7daf871b0189ecab8f483ab/sample/src/main/java/io/github/douglasjunior/androidSimpleTooltip/sample/MainActivity.java#L269-L282), and have no problem.

Demo:

![ezgif-4-10d3374e01](https://user-images.githubusercontent.com/1512341/35150234-c651b0aa-fd00-11e7-8b8a-0c915270f196.gif)

Code:

```java
            final SimpleTooltip tooltip = new SimpleTooltip.Builder(this)
                    .anchorView(v)
                    .text("your text")
                    .gravity(Gravity.TOP)
                    .animated(true)
                    .transparentOverlay(true)
                    .build();
            tooltip.show();
            mHandler.postDelayed(new Runnable() {
                @Override
                public void run() {
                    tooltip.dismiss();
                }
            }, 3000);
```

**Comment by desaibijon** [comment]
Hi @douglasjunior,
The animated property helped me dismiss the tooltip. Thanks for that. 

But, I want my tooltip to remain steady and not float up and down. Can you help me on that?

**Comment by douglasjunior** [comment]
Just set `.animated(false)`.

```java
            final SimpleTooltip tooltip = new SimpleTooltip.Builder(this)
                    .anchorView(v)
                    .text("your text")
                    .gravity(Gravity.TOP)
                    .animated(false)
                    .transparentOverlay(true)
                    .build();
            tooltip.show();
            mHandler.postDelayed(new Runnable() {
                @Override
                public void run() {
                    tooltip.dismiss();
                }
            }, 3000);
```

**Comment by shylendramadda** [comment]
@douglasjunior  Thank you it's working for me.

final SimpleTooltip tooltip = new SimpleTooltip.Builder(this)
                    .anchorView(v)
                    .text("your text")
                    .gravity(Gravity.TOP)
                    .animated(true)
                    .transparentOverlay(true)
                    .build();
            tooltip.show();
            mHandler.postDelayed(new Runnable() {
                @Override
                public void run() {
                    tooltip.dismiss();
                }
            }, 3000);
