### ISSUE TITLE
How to optimise the code instead each time calling same things

### ISSUE THREAD

**Issue by achaklashiya** [douglasjunior/android-simple-tooltip#63]
Hello Sir,
Below code is used as many time as we want to create a new tooltip.So rather than that, we can create a function and in that, we can pass a parameter as (String, int) for text and gravity.
Or maybe I am wrong so help me to figure out this problem.
new SimpleTooltip.Builder(this)
                    .anchorView(v)
                    .text(R.string.btn_animated)
                    .gravity(Gravity.TOP)
                    .animated(true)
                    .build()
                    .show();

**Comment by douglasjunior** [comment]
You can create a "helper/util class" thats contains static methods to create Tooltips.

Sample:

```java
public final class TooltipHelper {
       private TooltipHelper() {}

       public static SimpleTooltip makeMyAwesomeTooltip(Activity activity, View anchor, String text) {
              return new SimpleTooltip.Builder(activity)
              .anchorView(anchor)
              .text(text)
              .gravity(Gravity.TOP)
              .animated(true)
              .build();
       }
}
```

To use: 

```java
TooltipHelper.makeMyAwesomeTooltip(this, myButton, "Hello").show();
```

This will work like the Android `Toast` class.

**Comment by Akshar-Chaklashiya** [comment]
Thank you very much for give me your valuable time.
My problem is while one the tool pick is initialized, it will be removed by this method(dismissOnOutsideTouch(true),dismissOnInsideTouch(true),etc)That i know.but when i click on another button for tool pick, the previous one is also popped up.Below i write my code.I used static method suggested by 
![device-2018-01-23-175113](https://user-images.githubusercontent.com/32703725/35275517-0af1e6d6-0066-11e8-9666-4e3b199b6104.png)
you.
// android code
public class MainActivity extends AppCompatActivity implements View.OnClickListener {

    Button buttonTop;
    Button buttonCenter;
    Button buttonBottom;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        buttonTop = findViewById(R.id.buttonTop);
        buttonCenter = findViewById(R.id.buttonCenter);
        buttonBottom = findViewById(R.id.buttonBottom);

        buttonTop.setOnClickListener(this);
        buttonCenter.setOnClickListener(this);
        buttonBottom.setOnClickListener(this);
    }

    @Override
    public void onClick(View view) {

        switch (view.getId()) {

            case R.id.buttonBottom:
                TooltipHelper.createMyTooltip(MainActivity.this,buttonBottom, "Hello" , Gravity.TOP).show();
            case R.id.buttonCenter:
                TooltipHelper.createMyTooltip(MainActivity.this,buttonCenter, "Hello" , Gravity.TOP).show();
            case R.id.buttonTop:
                TooltipHelper.createMyTooltip(MainActivity.this,buttonTop, "Hello" , Gravity.BOTTOM).show();

        }
    } #

**Comment by Akshar-Chaklashiya** [comment]
Thank you very much for give me your valuable time.
My problem is while one the tool pick is initialized, it will be removed by this method(dismissOnOutsideTouch(true),dismissOnInsideTouch(true),etc)That i know.but when i click on another button for tool pick, the previous one is also popped up.Below i write my code.I used static method suggested by
device-2018-01-23-175113
you.
// android code
public class MainActivity extends AppCompatActivity implements View.OnClickListener {

Button buttonTop;
Button buttonCenter;
Button buttonBottom;


@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);

    buttonTop = findViewById(R.id.buttonTop);
    buttonCenter = findViewById(R.id.buttonCenter);
    buttonBottom = findViewById(R.id.buttonBottom);

    buttonTop.setOnClickListener(this);
    buttonCenter.setOnClickListener(this);
    buttonBottom.setOnClickListener(this);
}

@Override
public void onClick(View view) {

    switch (view.getId()) {

        case R.id.buttonBottom:
            TooltipHelper.createMyTooltip(MainActivity.this,buttonBottom, "Hello" , Gravity.TOP).show();
        case R.id.buttonCenter:
            TooltipHelper.createMyTooltip(MainActivity.this,buttonCenter, "Hello" , Gravity.TOP).show();
        case R.id.buttonTop:
            TooltipHelper.createMyTooltip(MainActivity.this,buttonTop, "Hello" , Gravity.BOTTOM).show();

    }
} #

**Comment by achaklashiya** [comment]
I resolved that issue.Thank you.
