### ISSUE TITLE
Set match parent width not working

### ISSUE THREAD

**Issue by tabassumLatif** [douglasjunior/android-simple-tooltip#64]
I have created a custom  layout with match parent width. But when i run my app  it gets shrink (the layout widths turn into wrap)

**Comment by douglasjunior** [comment]
Hi, thanks for the feedback.

Please, share your XML layout and the code snippets to create the tooltip.

**Comment by tabassumLatif** [comment]
The dimensions of your pop up window box are wrap_content, please make a function from where we can set the width of popup window box dynamically and also we are not able to apply margin left and margin right specifically on to the pop up window box.

**Comment by douglasjunior** [comment]
You don't need to set the width in the popup, by being `wrap_content`, it will adapt to the size of your content. So, you just need to set the width on your content and the popup will adapt.

To help you, please, share your XML layout and the code snippets to create the tooltip.

**Comment by tabassumLatif** [comment]
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:background="@color/colorWhite"
    android:orientation="vertical">


    <android.support.v7.widget.RecyclerView
        android:id="@+id/recyclerViewWeek"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"></android.support.v7.widget.RecyclerView>



This is my xml, i just simply want to be in match parent and when i run my app. it depends on the text inside my item list, although i have set already match_parent in my xml  , here is the xml of item list
 <TextView
        android:id="@+id/tvName"
        style="@style/textWeek"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"/>

**Comment by tabassumLatif** [comment]
<TextView
        android:id="@+id/tvName"
        style="@style/textWeek"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"/>

**Comment by douglasjunior** [comment]
Are you trying to use recycler as popup content? In this case I recommends that you use directly the [PopupWindow](https://developer.android.com/reference/android/widget/PopupWindow.html). This library was created with Tooltips in mind.
