### ISSUE TITLE
how to give an index in a textview to keep the anchor point at?

### ISSUE THREAD

**Issue by Fahad-pnw** [douglasjunior/android-simple-tooltip#67]
Hi, i'm using spannable string and the issue is i've multiple tooltips required.
i need a solution to that, may be if i'd somehow pass an index of a textview, i'd get the textview at the correct position, since you've worked on this, could you guide what must i change?

**Comment by douglasjunior** [comment]
You need to pass the `View` object. Do not have access to View?

**Comment by Fahad-pnw** [comment]
No access to the view. I mean, yes access to the parent view which is a
textview, i need to pop up at a spannable string which is inside of a
textview, it shows at the end of the textview so i need to pass position
somehow to the anchorpoint

**Comment by douglasjunior** [comment]
I understand, unfortunately it is not possible to pass a specific position.

**Comment by Fahad-pnw** [comment]
thanks for the reply. could you still guide where in the library, by editing in the library itself, i'd give hard code a position so tooltip always display there? i tried but couldnt find yet. so it would be helpful as you created this.

**Comment by Fahad-pnw** [comment]
i'd really need to study a lot before i could make the approp changes.
since you've been working on this for quite some time..


could you tell which constructor or line # would be helpful to override/pass x and y offsets or coordinates in here.

i'm trying to implement this for many days now and getting no where.

public void show() {
        verifyDismissed();

        mContentLayout.getViewTreeObserver().addOnGlobalLayoutListener(mLocationLayoutListener);
        mContentLayout.getViewTreeObserver().addOnGlobalLayoutListener(mAutoDismissLayoutListener);

        mRootView.post(new Runnable() {
            @Override
            public void run() {
                if (mRootView.isShown())
                    mPopupWindow.showAtLocation(mRootView, Gravity.NO_GRAVITY, mRootView.getWidth(), mRootView.getHeight());
                else
                    Log.e(TAG, "Tooltip cannot be shown, root view is invalid or has been closed.");
            }
        });
    }

**Comment by douglasjunior** [comment]
Hi @Fahad-pnw , sorry for delay, I'm very busy now.

Te location is calculated here: https://github.com/douglasjunior/android-simple-tooltip/blob/e5579c7cc82ca54f3a1e72dc79b4a705af6ea85c/library/src/main/java/io/github/douglasjunior/androidSimpleTooltip/SimpleTooltip.java#L233-L265

**Comment by Fahad-pnw** [comment]
No worries, i created a custom pop up and calling it upon spannables

**Comment by margin555** [comment]
@Fahad-pnw Does the custom pop up start from the same point where the icon is located in your textview? I am facing the same issue
