### ISSUE TITLE
Overlay not working at times

### ISSUE THREAD

**Issue by mkamals1989** [douglasjunior/android-simple-tooltip#68]
Hi,

I am using the overlay with modal(true) tooltip in some of my screens and it works perfectly fine as needed. But in some fragment the overlay is not showing and even the modal is not working. I don't see any difference in the code as I am using the same code which works in other fragments. I have added the code below which I am using and also the screenshot of that screen where the overlay is not showing. Can you find out if there is any bug in that?

     new SimpleTooltip.Builder(baseActivity)
                .anchorView(img_camera)
                .text("Tap here to change your profile pic!!!")
                .textColor(ContextCompat.getColor(baseActivity, R.color.colorToolBar))
                .backgroundColor(ContextCompat.getColor(baseActivity, R.color.colorWhite))
                .gravity(Gravity.TOP)
                .dismissOnInsideTouch(true)
                .dismissOnOutsideTouch(false)
                .modal(true)
                .arrowColor(ContextCompat.getColor(baseActivity, R.color.colorWhite))
                .arrowHeight(25.0f)
                .arrowWidth(25.0f)
                .animated(true)
                .animationDuration(800)
                .transparentOverlay(false)
                .build()
                .show();

![device-2018-03-18-164949](https://user-images.githubusercontent.com/21290326/37565277-7127f9be-2acc-11e8-8b4f-66f3bff0f850.png)

Thanks in advance.

**Comment by douglasjunior** [comment]
Overlay automatically tries to search the View that is parent of all.

Maybe something in your View structure has different than is expected.

Look here:

https://github.com/douglasjunior/android-simple-tooltip/blob/225839ddba3bcb8ec456bf4936f0100cd7e16299/library/src/main/java/io/github/douglasjunior/androidSimpleTooltip/SimpleTooltipUtils.java#L176-L182
