### ISSUE TITLE
How to  hide Tooltip on Click

### ISSUE THREAD

**Issue by ravirajjak** [douglasjunior/android-simple-tooltip#70]
Hi, How would you hide tooltip on click of another view?

**Comment by douglasjunior** [comment]
The view you clicked, is it inside or outside the tooltip?

If is outside, use `modal(false)` and `dismissOnOutsideTouch(true)`.

If is inside, see thesample project:

https://github.com/douglasjunior/android-simple-tooltip/blob/b298452ebc7e91189292891f4972c5514e85156f/sample/src/main/java/io/github/douglasjunior/androidSimpleTooltip/sample/MainActivity.java#L163-L194
