### ISSUE TITLE
Dismiss listener functionality

### ISSUE THREAD

**Issue by saurabhdhillon** [douglasjunior/android-simple-tooltip#80]
I just implemented android-simple-tooltip and got across wierd issue. I need to dismiss the tool-tip on fragment close but without OnDismissListener listener invoked so that i can show it again when i reume the fragment, it should rather be invoked only on tool-tip click
The issue is in  `tooltip.dismiss()` function, it fires  the dismiss listener which should effectively be invoked only on tooltip clicked when i have enabled `dismissOnInsidetouch`

Below is the code where i maintain a boolean value in shared preferences for each tool-tip with creation and its value is toggled when Dismiss listener fires.

```
public static SimpleTooltip createTip(View anchorView, int gravity, String text,
                                          String preferenceId,  SimpleTooltip.OnDismissListener listener) {
        if (SharedPrefUtils.getBooleanSharedPreference(anchorView.getContext(), preferenceId, false)) {
           //preference id stores the visibility toggle which should toggle only on tip click 
            return null;
           }
           return new SimpleTooltip.Builder(anchorView.getContext())
           .anchorView(anchorView)
           .text(text)
           .gravity(gravity)
           .animated(true)
           .backgroundColor(ContextCompat.getColor(anchorView.getContext(), R.color.orange_primary))
           .transparentOverlay(true)
           .onDismissListener(listener)
           .arrowColor(ContextCompat.getColor(anchorView.getContext(), R.color.orange_primary))
            .dismissOnInsideTouch(true)
           .dismissOnOutsideTouch(false)
            .textColor(ContextCompat.getColor(anchorView.getContext(), R.color.white))
            .build();
    }
```

This is the dismiss listener implemented where i toggle the value in shared preferences
```
@Override
    public void onDismiss(SimpleTooltip tooltip) {
        SharedPrefUtils.saveBooleanSharedPreferences(context,
                context.getString(R.string.floor_change_tip_preference_id), true);
    }
```

**Comment by douglasjunior** [comment]
You can not avoid the dismiss listener call. You will need to control your event in another way, for example, when closing your fragment.

**Comment by saurabhdhillon** [comment]
I have added the fix for the same please refer to the pull request mentioned above.

**Comment by douglasjunior** [comment]
I think that this is not a library responsibility. You can wrap this behavior on a separated class.

**Comment by saurabhdhillon** [comment]
Better the cases handled, better is the library to use.

**Comment by douglasjunior** [comment]
Sorry, but I disagree. I prefer to keep things as [simple and generic as possible](https://en.wikipedia.org/wiki/KISS_principle).

**Comment by saurabhdhillon** [comment]
Great, no issues :+1:
