### ISSUE TITLE
prevent the click event propagation to the views under the OverlayView

### ISSUE THREAD

**Issue by mario-dario** [douglasjunior/android-simple-tooltip#84]
@douglasjunior
How can I prevent the click event propagation to the views under the Overlay-view ?
I mean, when the view is on top, before dismiss, I want to prevent the click to propagate together with the dismiss click.
I have a button underneath the overlay which opens another activity, and its being clicked when clicking the overlay.
The only workaround I have found is to prevent the dismissal on outside click altogether.
Any Idea?
Any idea?

**Comment by douglasjunior** [comment]
> How can I prevent the click event propagation to the views under the Overlay-view ?

You need to set the `modal` property.
