### ISSUE TITLE
How to use the Tooltip in the project

### ISSUE THREAD

**Issue by jt4000** [douglasjunior/android-simple-tooltip#86]
Goal:
use this tooltip in my android project.

Problem:
I dont know I have made the correct settings in order to use the tooltip.

What part am I missing?

Thank you!

![tooltip1](https://user-images.githubusercontent.com/14993569/45932988-83f18800-bf85-11e8-9480-480df3aa20c1.png)
![tooltip2](https://user-images.githubusercontent.com/14993569/45932989-848a1e80-bf85-11e8-84ad-1297f5e888ca.png)

**Comment by douglasjunior** [comment]
The repository is in the wrong place.

See this example: https://github.com/douglasjunior/android-simple-tooltip/blob/master/build.gradle#L21
