### ISSUE TITLE
Android Espresso test case issues finding the tooltip as part of the hierarchy

### ISSUE THREAD

**Issue by brutalrisk** [douglasjunior/android-simple-tooltip#88]
Am I testing with espresso framework wrong?  The application I am testing is using the tooltip library and I have used the onview(withId(R.id.OK)).perform(click()) method to see if does a click in the tool tip pop up screen, but it fails because the view is not part of the hierarchy of the application.

So then I tested with the inroot methods since I saw a closed issue you mention that the tooltip behaves as an android dialog. so I did the following:

onView(withText("OK"))
                .inRoot(isDialog()) // <---
                .perform(click());

but it still gives me that it cannot find the view to do the action.

#30 is the issue that was closed which I would like to follow up from.

**Comment by douglasjunior** [comment]
This library was created with the [PopupWindow](https://developer.android.com/reference/android/widget/PopupWindow). So, you need to handle the tests on internal components just like any other PopupWindow.

**Comment by douglasjunior** [comment]
Take a look https://stackoverflow.com/questions/27382147/write-a-test-that-clicks-on-views-inside-popupwindow

**Comment by brutalrisk** [comment]
@douglasjunior thank you so much for the help.  This solved my problem. I thought it was a Dialog based on your previous comment from the last closed issue.  The pop up window method helped.
I appreciate the responds.
