### ISSUE TITLE
change text font of tooltip

### ISSUE THREAD

**Issue by rameez-sgi** [douglasjunior/android-simple-tooltip#89]
can we change font of text on tool tip ?

**Comment by douglasjunior** [comment]
Yes, but you need to set a custom `contentView ` to do this.

See this example:
https://github.com/douglasjunior/android-simple-tooltip/blob/ff64700584f9d2a9f945bd100653c6cb103f1ce0/sample/src/main/java/io/github/douglasjunior/androidSimpleTooltip/sample/MainActivity.java#L166-L196

**Comment by rameez-sgi** [comment]
ok thanks i will try this

**Comment by rameez-sgi** [comment]
it worked ! thanks
