### ISSUE TITLE
Has simple-tooltip possibility to draw round corners of the tooltip?

### ISSUE THREAD

**Issue by panovvitalik** [douglasjunior/android-simple-tooltip#93]

**Comment by nazeerahamed23** [comment]
I have also same problem, can u pls help?

**Comment by panovvitalik** [comment]
I leave squar corners :-(

**Comment by douglasjunior** [comment]
Please, take a look at the Custom Tooltip Sample.

![image](https://user-images.githubusercontent.com/1512341/51312951-995a5880-1a33-11e9-9555-cd38df1ee6a2.png)


Code: 

https://github.com/douglasjunior/android-simple-tooltip/blob/cd70d91507cb64749c73f99e3254836190a6c568/sample/src/main/java/io/github/douglasjunior/androidSimpleTooltip/sample/MainActivity.java#L166-L178

Layout:

https://github.com/douglasjunior/android-simple-tooltip/blob/cd70d91507cb64749c73f99e3254836190a6c568/sample/src/main/res/layout/tooltip_custom.xml#L2-L7

Background:

https://github.com/douglasjunior/android-simple-tooltip/blob/cd70d91507cb64749c73f99e3254836190a6c568/sample/src/main/res/drawable/bg_tooltip.xml#L1-L5

**Comment by nazeerahamed23** [comment]
Thanks a lot..

**Comment by binaykumarrana** [comment]
Hi,
I am applying custom tooltip but not working instead the size of tooltip is small without text displaying.

I tried passing android.R.id.text1 as well as own textview but in both case not working.

I used above tooltip_custom.xml layout.

Anything I am missing?

Thanks 
Binay
