### ISSUE TITLE
How to set margins the right way?

### ISSUE THREAD

**Issue by justbyter** [douglasjunior/android-simple-tooltip#98]
Currently setting the margins via the Builder only affects the offset from the anchor. It doesn't apply margins on all sides. Is there a way to solve this?

 I tried setting the margins for the mContentLayout but it doesn't work.

**Comment by douglasjunior** [comment]
Where exactly do you want to add margins?

**Comment by justbyter** [comment]
@douglasjunior I want to add it to all sides. I tried adding layout_margins in my contentView XML, it does nothing. I tried using the margins parameter in the builder, but it only adds it on the side where the arrow points.

**Comment by shylendramadda** [comment]
Any update on this?
