### ISSUE TITLE
I have used tooltip in fragment & i want to dismiss tooltip on activity back pressed

### ISSUE THREAD

**Issue by poo0392** [douglasjunior/android-simple-tooltip#99]
Need a help, I have a fragment where on textview i have showed tooltip, but now when i click back , the tooltip shows open, how can i close it from activity.

**Comment by Sakulkarketan** [comment]
this still happining in version 1.1.0 can You please provide some solution to this
![Uploading Screenshot 2024-06-21 at 8.32.28 PM.png…]()
